version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # change to your runtime
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the application...
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
